# Etherpad
version: '3'

networks:
  etherpad:
    external: false

services:
  etherpad:
    image: etherpad/etherpad
    ports: 
      - "127.0.0.1:9001:9001"
    restart: unless-stopped
    networks:
      - etherpad
    environment:
      - TITLE=pad
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_PASS=daprehte
      - ADMIN_PASSWORD=
    depends_on:
      - "db"

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
    environment:
      - POSTGRES_USER=etherpad
      - POSTGRES_PASSWORD=daprehte
      - POSTGRES_DB=etherpad
    networks:
      - etherpad

volumes:
  db_data:

