# Etherpad
version: '3'

networks:
  etherpad:
    external: false

services:
  etherpad:
    restart: unless-stopped
    image: local/etherpad
    ports:
      - "127.0.0.1:9003:9001"
    networks:
      - etherpad
    environment:
      - TITLE=pad
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=etherpad
      - DB_USER=etherpad
      - DB_PASS=daprehte
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=etherpad
      - POSTGRES_PASSWORD=daprehte
      - POSTGRES_DB=etherpad
    networks:
      - etherpad

  pgadmin:
    image: dpage/pgadmin4:4.23
    networks:
      - etherpad
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin:
